mysite/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('game/', include('game.urls')),
    path('', base_views.startpage, name='startpage'),  # '/' 에 해당되는 path
]
# settings.py 경로의 urls.py
from django.conf.urls.static import static
...
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/game/urls.py
from django.urls import path
from .import views

app_name = 'game'
urlpatterns = [
    path('<int:pk>/detail/', views.GameDetailView.as_view(), name='detail'),
    path('create/', views.GameCreateView.as_view(), name='game_create'),
    path('<int:pk>/update/', views.GameUpdateView.as_view(), name='game_update'),
    path('<int:pk>/delete/', views.game_delete, name='game_delete'),
    path('<int:pk>/comment/write/', views.comment_write, name='comment_write'),
    path('<int:pk>/comment_delete/', views.comment_delete, name='comment_delete'),
    path('<int:pk>/like/', views.like, name='like'),
    path('list/', views.game_list, name='list'),
    path('search/', views.game_search, name='search'),
]

mysite/game/models.py
from django.db import models
from embed_video.fields import EmbedVideoField
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.contrib.auth.models import User
from config import settings

# Create your models here.
class Game(models.Model):
    app_id = models.IntegerField(verbose_name='app_id', null=True, blank=True)
    title = models.CharField(verbose_name='title', max_length=100)
    genre = models.CharField(verbose_name='genre', max_length=100)
    developer = models.CharField(verbose_name='developer', max_length=100)
    release_at = models.DateTimeField(verbose_name='release Day')
    info = models.TextField(verbose_name='info')
    video = EmbedVideoField(null=True)

    thumbnail = ProcessedImageField(
        upload_to='thumbnail',
        processors=[ResizeToFill(220, 70)],
        format='JPEG',
        options={'qualtiy': 80},
        blank=True
    )
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_game')
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']

class Genre_list(models.Model):
    genre_list = models.CharField(verbose_name='genre_list', max_length=100)

    def __str__(self):
        return self.genre_list


class Comment(models.Model):
    post= models.ForeignKey(Game, on_delete=models.CASCADE, null=True, related_name='comments')
    comment_date= models.DateTimeField(auto_now_add=True)
    comment_contents=models.CharField(max_length=200)
    comment_writer= models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='game_comment_writer')

    class Meta:
        ordering=['-id']

mysite/game/forms.py
from django import forms
from .models import  Game, Genre_list

class GameCreateForm(forms.ModelForm):
    genre_choice = forms.ModelMultipleChoiceField(queryset=Genre_list.objects.all(),
                                                  widget=forms.CheckboxSelectMultiple)
    class Meta:
        model = Game
        fields = ['title', 'genre_choice', 'developer', 'release_at', 'info', 'thumbnail', 'video']

    def save(self, commit=True):
        game = self.instance
        genre_list = '/'.join([qs.genre_list for qs in self.cleaned_data['genre_choice']])
        game.genre = genre_list
        game.save()
        return game

mysite/game/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from .models import Game, Genre_list, Comment
from .forms import GameCreateForm
from django.shortcuts import redirect, render
from django.urls import reverse
from django.core.paginator import Paginator
from django.db.models import Q

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class GameDetailView(DetailView):
    template_name = 'game/game_detail.html'
    model = Game
class GameCreateView(CreateView):
    template_name = 'game/game_create.html'
    form_class = GameCreateForm

    def get_success_url(self):
        return reverse('game:detail', args=[self.object.pk])

class GameUpdateView(UpdateView):
    template_name = 'game/game_update.html'
    form_class = GameCreateForm
    model = Game

    def get_success_url(self):
        return reverse('game:detail', args=[self.object.pk])

def game_delete(request, pk):
    game = Game.objects.get(pk=pk)
    game.delete()
    return redirect(reverse('game:list'))

def game_list(request):
    paginate_by = 7;
    context = {}

    context['is_paginated']=True

    all_games = Game.objects.all()
    paginator = Paginator(all_games, paginate_by)
    page_number_range = 5
    current_page = int(request.GET.get('page', 1))
    context['current_page']=current_page

    start_index = int((current_page-1)/page_number_range)*page_number_range
    end_index = start_index + page_number_range

    current_page_group_range = paginator.page_range[start_index : end_index]
    print("current_page_group_range", current_page_group_range)

    start_page = paginator.page(current_page_group_range[0])
    end_page = paginator.page(current_page_group_range[-1])

    has_previous_page = start_page.has_previous()
    has_next_page = end_page.has_next()

    context['current_page_group_range'] = current_page_group_range
    if has_previous_page:
        context['has_previous_page'] = has_previous_page
        context['previous_page'] = start_page.previous_page_number

    if has_next_page:
        context['has_next_page'] = has_next_page
        context['next_page'] = end_page.next_page_number

    e = paginate_by * current_page
    s = e - paginate_by
    print("내용 index", s, e)
    game_list = Game.objects.all()[s:e]

    genre_list = Genre_list.objects.all()
    context['genre_list'] = genre_list
    context['game_list'] = game_list

    return render(request, 'game/game_list.html', context)

def game_search(request):
    paginate_by = 7
    context = {}
    game_list = Game.objects.all()

    b = request.GET.get('b','')
    f = request.GET.getlist('f')


    if f:
        print(f)
        query = Q()
        for i in f:
            query = query | Q(genre__icontains=i)
            game_list = game_list.filter(query)
    if b:
        print(b)
        game_list = game_list.filter(Q(title__icontains=b) | Q(developer__icontains=b))
    context['is_paginated'] = True

    paginator = Paginator(game_list, paginate_by)
    page_number_range = 5
    current_page = int(request.GET.get('page', 1))
    context['current_page'] = current_page

    start_index = int((current_page-1)/page_number_range)*page_number_range
    end_index = start_index + page_number_range

    current_page_group_range = paginator.page_range[start_index : end_index]
    print("current_page_group_range", current_page_group_range)

    start_page = paginator.page(current_page_group_range[0])
    end_page = paginator.page(current_page_group_range[-1])

    has_previous_page = start_page.has_previous()
    has_next_page = end_page.has_next()

    context['current_page_group_range'] = current_page_group_range
    if has_previous_page:
        context['has_previous_page'] = has_previous_page
        context['previous_page'] = start_page.previous_page_number

    if has_next_page:
        context['has_next_page'] = has_next_page
        context['next_page'] = end_page.next_page_number()

    genre_list = Genre_list.objects.all()
    context['genre_list'] = genre_list

    e = paginate_by * current_page
    s = e - paginate_by
    print("내용 index", s, e)

    game_list = game_list[s:e]
    context['game_list'] = game_list

    return render(request, 'game/game_search.html', context)

@login_required(login_url='common:login')
def comment_write(request,pk):
    if request.method == 'POST':
        post = get_object_or_404(Game, pk=pk)
        content = request.POST.get('content')
        conn_user = request.user
        Comment.objects.create(post=post, comment_writer=conn_user, comment_contents=content)
        return redirect(reverse('game:detail', args=[pk]))
@login_required(login_url='common:login')
def comment_delete(request, pk):
    comment = Comment.objects.get(pk=pk)
    game_pk = comment.post.pk

    if comment.comment_writer == User.objects.get(username = request.user.get_username()):
        comment.delete()
        return redirect(reverse('game:detail', args=[game_pk]))
    else :
        return redirect(request, 'game/game_detail.html', {'comment':comment, "auth_error":"'해당댓글에 대한 삭제 권한이 없습니다."})

@login_required(login_url='common:login')
def like(request, pk):
    game = get_object_or_404(Game, id=pk)

    if request.user in game.like_users.all():
        game.like_users.remove(request.user)
    else:
        game.like_users.add(request.user)

    return redirect('game:detail', pk = pk)

mysite/templates/game/game_create.html
{% extends 'base.html' %}
{% block title %} GAME REGISTER {% endblock title %}
{% block content %}

<form method="post">
  {% csrf_token %}

  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      {% if field.name != 'genre_choice' %}
      <p>{{field.label}} : {{field}}</p>
      {%else%}
      <p>
          {{field.label}} :
          {% for check in form.genre_choice %}
          {{check}}
          {% endfor %}
      </p>
      {% endif %}
      {% endfor %}
      <p>
          <button type = 'submit' class = 'btn btn-primary'> REGISTERATION </button>
      </p>

  </form>
</form>

{% endblock content %}

mysite/templates/game/game_detail.html
{% extends 'base.html' %}
{% block title %} GAME_DETAIL {% endblock title %}
{% block content %}
<head>
    <script src="https://kit.fontawesome.com/0c005e78f1.js" crossorigin="anonymous"></script>
</head>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <br>
            <h6 style="color: #808080">모든 게임 >  {{game.genre}}</h6>
            <h2 style="color: #F5AB00">{{game.title}}</h2>

            <p style="color: #000000">좋아요 :
            <a href="{% url 'game:like' game.id %}"></a>
            {% if user in game.like_users.all %}
            <a href="{% url 'game:like' game.id %}"><i class="fa-solid fa-heart" style="color: #0259ed;"></i></a>
            {% else %}
            <a href="{% url 'game:like' game.id %}"><i class="fa-solid fa-heart" style="color: #f01414;"></i></a>
            {% endif %}
            &nbsp;&nbsp;&nbsp;&nbsp; {{ game.like_users.count }} 명이 좋아합니다.</p>
            <br>
        </div>
        <div class="col-md-7">
            {% load embed_video_tags %}
            {% video game.video '100% x 100%' %}
        </div>
        <div class="col-md-5">
            <div class="tabbable" id="tabs-442371">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link active" href="#tab1" data-toggle="tab" style="color: #F5AB00">개요</a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="tab1">
                        <p>
                            <dt>출시일</dt>
                            <dd>{{game.release_at}}</dd>
                            <dt>개발사</dt>
                            <dd>{{game.developer}}</dd>
                            <dt>장르</dt>
                            <dd>{{game.genre}}</dd>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <br>
                <br>
                <h4 style="color: #000000">게임 소개</h4>
                <p style="color: #000000">
                    {{game.info}}
                </p>
            </div>
        </div>
        <div align="left" class="col-md-12 offset-md-0">
                <br>
                <br>
                <h4>댓글</h4>
                <br>
            </div>
{% for comment in game.comments.all %}
            <div class="col-md-12 offset-md-0" style="border-radius: 10px; marin-bottom: 20px; padding: 40px; background-color: #101010">
                <div class="comment">
                    <h5 style="color: #CDCDCD">작성자: {{ comment.comment_writer }}</h5>
                    <div class="date" style="color: #606060">{{ comment.comment_date }}</div>
                    <br>
                    <p style="color: #CDCDCD">{{ comment.comment_contents }}</p>
                    <a href="{% url 'game:comment_delete' comment.pk %}" style="font-weight: bold" class="btn btn-warning" onclick="return confirm('이 글을 삭제 하겠습니까?')">삭제</a>
                </div>
                {% empty %}
                <div class="col-md-12 offset-md-0">
                    <p style="color: #FFFFF">첫 번째 댓글을 작성해 보세요.</p>
                </div>
                {% endfor %}
                <div class="col-md-12 offset-md-0"><br></div>
                <div class="col-md-12 offset-md-0" style="border-radius: 10px; padding: 40px; background-color: #101010">
                    <h6 style="color: #CDCDCD">새 댓글 등록</h6>
                    <br>
                    <form action="{% url 'game:comment_write' game.pk %}" method="POST">
                        {% csrf_token %}
                        <input type="text" class="form-control" name="content" placeholder="댓글을 입력해 주세요.">
                        <br>
                        <input style="font-weight: bold" class="btn btn-warning" type="submit" value="등록">
                    </form>
                </div>
            </div>
    </div>
</div>
<br>
<br>
<br>
<br>
{% if user.is_superuser %}
<div class="row">
    <div class="col text-center">
        <a href="{%url 'game:game_update' game.pk %}" class="btn btn-warning" style="font-weight:bold">수정</a>&nbsp;
        <a href="{%url 'game:game_delete' game.pk %}" class="btn btn-warning" onclick="return confirm('이 글을 삭제 하겠습니까')" style="font-weight:bold">삭제</a>
    </div>
</div>
{% endif %}
{% endblock content %}

mysite/templates/game/game_list.html
{% extends 'base.html' %}
{% block title %} GAME LIST {% endblock title %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block sidebar collapse" style="background-color: #666666">
            <div class="sidebar-sticky pt-3">
                <ul class="nav flex-column">
                    <table class = 'table' style="background-color: #000000; color: #ffffff">
                        <br>
                        <thead>
                        <h5>게임 찾기</h5>
                        </thead>
                        <br>
                        <tbody>
                        <form class="form-inline my-2 my-md-0" method="get" action="{% url 'game:search' %}">
                            <input class="form-control" type="text" placeholder="게임 이름, 개발사를 입력하세요" aria-label="Search" name="b" value="{{b}}">
                            <br>
                            {% for g in genre_list %}
                            <div class="form-check form-check-inline">
                                &nbsp;&nbsp;&nbsp;
                                <input class="form-check-input" type="checkbox" id="inlineCheckbox3" name="f", value="{{g}}">
                                <class class="form-check-label" for="inlineCheckbox5" style="color: #000000">{{g}}</class>
                            </div>
                            {% endfor %}
                            <br>

                            <button type="submit" class="btn btn-warning" style="font-weight: bold">검색</button>
                        </form>
                        </tbody>
                    </table>
                </ul>
            </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
            <br>
            <h2>게임 목록</h2>
            <br>
            <table class = 'table' style="color: #ffffff">
                <thead style="background-color: #000000">
                <tr align="center">
                    <th scope="col">게임 이미지</th>
                    <th scope="col">게임 이름</th>
                    <th scope="col">개발사</th>
                </tr>
                </thead>
                <tbody style="background-color: #353535">
                {% for game in game_list %}
                <tr align = "center">
                    <td style="padding:5px">
                        {% if game.thumbnail %}
                        <img src="{{game.thumbnail.url}}" class="thumbnails">
                        {% endif %}
                    </td>
                    <td style="padding:5px">
                        <a href="{% url 'game:detail' game.pk %}" style="color: #FFC107"><br>{{game.title}}</a>
                    </td>
                    <td style="padding:5px; color: #CDCDCD"><br>
                        {{game.developer}}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <br>
            <br>

            <div class="container-fluid text-center">
                {% if is_paginated %}
                <p>
                    {% if has_previous_page %}
                <a href='/game/search?b={{request.GET.b}}&f={{request.GET.f}}&price={{request.GET.price}}&page={{previous_page}}' style="color: #000000">◀ 이전 페이지</a>
                {% endif %}
                &nbsp;
                {% for page in current_page_group_range %}
                &nbsp;
                {% if page == page_obj.number %}
                <a style="color: #000000">{{page}}</a>
                {% else %}
                <a href='/game/search?b={{request.GET.b}}&f={{request.GET.f}}&price={{request.GET.price}}&page={{page}}' style="color: #000000">
                    {{page}}
                </a>
                {% endif %}
                &nbsp;
                {% endfor %}
                &nbsp;
                {% if has_next_page %}
                <a href='/game/search?b={{request.GET.b}}&f={{request.GET.f}}&price={{request.GET.price}}&page={{next_page}}' style="color: #000000">다음 페이지 ▶</a>
                {% endif %}
                </p>
                {% endif %}
                <br>
                <br>
                <br>
            </div>
        </main>
    </div>
</div>
{% endblock content %}

mysite/templates/game/game_search.html
{% extends 'base.html' %}
{%block title%} SEARCH RESULT {%endblock title%}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block sidebar collapse" style="background-color: #666666">
            <div class="sidebar-sticky pt-3">
                <ul class="nav flex-column">
                    <table class = 'table' style="background-color: #000000; color: #ffffff">
                        <br>
                        <thead>
                        <h5>게임 찾기</h5>
                        </thead>
                        <br>
                        <tbody>
                        <form class="form-inline my-2 my-md-0" method="get" action="{% url 'game:search' %}">
                            <input class="form-control" type="text" placeholder="게임 이름, 개발사를 입력하세요" aria-label="Search" name="b" value="{{b}}">
                            <br>
                            {% for g in genre_list %}
                            <div class="form-check form-check-inline">
                                &nbsp;&nbsp;&nbsp;
                                <input class="form-check-input" type="checkbox" id="inlineCheckbox3" name="f", value="{{g}}">
                                <class class="form-check-label" for="inlineCheckbox5" style="color: #000000">{{g}}</class>
                            </div>
                            {% endfor %}
                            <br>

                            <button type="submit" class="btn btn-warning" style="font-weight: bold">검색</button>
                        </form>
                        </tbody>
                    </table>
                </ul>
            </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
            <br>
            <h2>검색 결과</h2>
            <br>
            <table class = 'table' style="color: #ffffff">
                <thead style="background-color: #000000">
                <tr align="center">
                    <th scope="col">게임 이미지</th>
                    <th scope="col">게임 이름</th>
                    <th scope="col">개발사</th>
                </tr>
                </thead>
                <tbody style="background-color: #353535">
                {% for game in game_list %}
                <tr align = "center">
                    <td style="padding:5px">
                        {% if game.thumbnail %}
                        <img src="{{game.thumbnail.url}}" class="thumbnails">
                        {% endif %}
                    </td>
                    <td style="padding:5px">
                        <a href="{% url 'game:detail' game.pk %}" style="color: #FFC107"><br>{{game.title}}</a>
                    </td>
                    <td style="padding:5px; color: #CDCDCD"><br>
                        {{game.developer}}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <br>
            <br>

            <div class="container-fluid text-center">
                {% if is_paginated %}
                <p>
                    {% if has_previous_page %}
                <a href='/game/search?b={{request.GET.b}}&f={{request.GET.f}}&price={{request.GET.price}}&page={{previous_page}}' style="color: #000000">◀ 이전 페이지</a>
                {% endif %}
                &nbsp;
                {% for page in current_page_group_range %}
                &nbsp;
                {% if page == page_obj.number %}
                <a style="color: #ffffff">{{page}}</a>
                {% else %}
                <a href="/game/search?b={{request.GET.b}}&f={{request.GET.f}}&price={{request.GET.price}}&page={{page}}" style="color: #000000">
                    {{page}}
                </a>
                {% endif %}
                &nbsp;
                {% endfor %}
                &nbsp;
                {% if has_next_page %}
                <a href="/game/search?b={{request.GET.b}}&f={{request.GET.f}}&price={{request.GET.price}}&page={{next_page}}" style="color: #000000">다음 페이지 ▶</a>
                {% endif %}
                </p>
                {% endif %}
                <br>
                <br>
                <br>
            </div>
        </main>
    </div>
</div>
{% endblock content %}

mysite/templates/game/game_update.html
{% extends "base.html" %}
{% block title %}게임정보 수정{% endblock title %}
{% block content %}
<h1>제품정보 수정</h1>
<form method="post">
  {% csrf_token %}
  <table>
    {{form.as_table}}
  </table>
  <p>
    <button type="submit" class="btn btn-primary">UPDATE</button>
  </p>
</form>
{% endblock content %}