mysite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

mysite/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('game/', include('game.urls')),
    path('', base_views.startpage, name='startpage'),  # '/' 에 해당되는 path
]
# settings.py 경로의 urls.py
from django.conf.urls.static import static
...
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/game/urls.py
from django.urls import path
from .import views

app_name = 'game'
urlpatterns = [
    path('<int:pk>/detail/', views.GameDetailView.as_view(), name='detail'),
    path('create/', views.GameCreateView.as_view(), name='game_create'),
    path('<int:pk>/update/', views.GameUpdateView.as_view(), name='game_update'),
    path('<int:pk>/delete/', views.game_delete, name='game_delete'),
    path('<int:pk>/comment/write/', views.comment_write, name='comment_write'),
    path('<int:pk>/comment_delete/', views.comment_delete, name='comment_delete'),
    path('<int:pk>/like/', views.like, name='like'),
    path('list/', views.game_list, name='list'),
    path('search/', views.game_search, name='search'),
]

mysite/pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [
    path('',
         base_views.startpage, name='startpage'),
    path('introduce',
         base_views.intro, name='introduce'),
    # base_views.py
    path('community',
         base_views.index, name='index'),
    path('<int:question_id>/',
         base_views.detail, name='detail'),

    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),

]

mysite/pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from ..models import Question

def startpage(request):
    return render(request, 'home.html')
def intro(request):
    return render(request, 'introduce.html')
def index(request) :
    """
    pybo 목록 출력
    """
    page = request.GET.get('page', '1')  # 페이지
    question_list = Question.objects.order_by('-create_date')
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    return render(request, 'pybo/question_list.html', context)
def detail(request, question_id):
    """
    pybo 내용 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question' : question}
    return render(request, 'pybo/question_detail.html', context)

mysite/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Game Scouter</title>

    <style>
        .bd-placeholder-img {
           font-size: 1.125rem;
           text-anchor: middle;
           -webkit-user-select: none;
           -moz-user-select: none;
           -ms-user-select: none;
           user-select: none;
           }

           @media (min-width: 768px) {
              .bd-placeholder-img-lg {
                 font-size: 3.5rem;
              }
           }

           table {border-collapse: collapse;}

           td {border-bottom: 5px solid #202020;}
    </style>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<script src="{% static 'bootstrap.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

mysite/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

mysite/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
    .box {
     background-image: url("{% static 'images/LoA.jpg' %}");
     background-size: cover;
     color: white;
}
</style>
<div class="box">
</div>
<div class="container">
  <div class="box">
    <h1 class="text-center" style="font-weight: bold">겜스에 오신 것을 환영합니다.</h1>
    <br>
    <p class="text-center">겜스는 게임 리뷰 사이트입니다.</p>
    <p class="text-center">원하는 게임의 리뷰를 확인해 보세요!</p>
    <br>
    <br>
    <p class="text-center"><a class="btn btn-warning" href="http://127.0.0.1:8000/game/list/" role="button" style="font-weight: bold">자세히 알아보기</a></p>
  </div>
</div>

<br>
<br>

<div class="container">
    <h3 class="text-left">최고의 신작</h3>
    <br>
    <div class="row">
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm" style="background-color: #000000">
                <img src="{% static 'images/Diablo4.jpg' %}" class="card-img-top" height="206"  alt="Diablo4">
                <div class="card-body">
                    <p class="card-text" style="color: #CDCDCD">세 명의 영웅이 이 땅을 잠식하고 있는 형언 불가능한 공포와 맞서 싸울 준비를 마쳤습니다. 악의 군대와 맞서며 잊혀진 비밀을 밝혀내십시오. 세상의 운명이 당신의 손에 달려 있습니다.</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="http://127.0.0.1:8000/game/1/detail/" class="btn btn-warning" style="font-weight: bold">자세히 보기</a>
                        </div>
                        <small class="text-muted" style="text-align: right"></small>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm" style="background-color: #000000">
                <img src="{% static 'images/Zelda_TK.jpg' %}" class="card-img-top" height="206"  alt="Zelda_TK">
                <div class="card-body">
                    <p class="card-text" style="color: #CDCDCD">끝없는 모험의 무대가 하늘로 넓어진다. 『젤다의 전설 브레스 오브 더 와일드』 속편이 등장 하늘에 떠 있는 섬들, 처음 보는 무기, 신기한 탈것… 도대체 하이랄에 무슨 일이 일어난 것인가? 당신만의 끝없는 모험이 ….</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="http://127.0.0.1:8000/game/2/detail/" class="btn btn-warning" style="font-weight: bold">자세히 보기</a>
                        </div>
                        <small class="text-muted" style="text-align: right"></small>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm" style="background-color: #000000">
                <img src="{% static 'images/hogwarts_legacy.jpg' %}" class="card-img-top"  height="206"  alt="hogwarts_legacy">
                <div class="card-body">
                    <p class="card-text" style="color: #CDCDCD">호그와트 레거시는 해리 포터 세계관에서 진행되는 몰입형 오픈월드 액션 RPG입니다. 그 누구도 경험하지 못한, 1800년대의 호그와트를 경험하세요. 플레이어는 마법 세계를 산산조각낼 위험이 있는 오래된 ... </p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="http://127.0.0.1:8000/game/3/detail/" class="btn btn-warning" style="font-weight: bold">자세히 보기</a>
                        </div>
                        <small class="text-muted" style="text-align: right"></small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<br>
<br>

<div class="container">
    <h3 class="text-left">금주의 추천 게임</h3>
    <br>
    <div class="row">
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm" style="background-color: #000000">
                <img src="{% static 'images/minecraft.jpg' %}" class="card-img-top"   height="206"  alt="minecraft">
                <div class="card-body">
                    <p class="card-text" style="color: #CDCDCD">마인크래프트는 모장 AB의 설립자 마르쿠스 페르손이 만든 샌드박스 건설 게임으로 삼차원 세상에서 다양한 블록을 놓고 부수면서 여러 구조물과 작품을 만들 수 있으며, 싱글플레이어와 멀티플레이어를 ...</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="http://127.0.0.1:8000/game/13/detail/" class="btn btn-warning" style="font-weight: bold">자세히 보기</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm" style="background-color: #000000">
                <img src="{% static 'images/lol.jpg' %}" class="card-img-top"   height="206"  alt="lol">
                <div class="card-body">
                    <p class="card-text" style="color: #CDCDCD">리그 오브 레전드는 세계 최고의 MOBA(Multiplayer Online Battle Arena) 게임입니다. 끝없이 이어지는 실시간 전투와 협동을 통한 팀플레이, RTS와 RPG를 하나의 게임에서 동시에 즐길 수 있는 ...</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="http://127.0.0.1:8000/game/14/detail/" class="btn btn-warning" style="font-weight: bold">자세히 보기</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm" style="background-color: #000000">
                <img src="{% static 'images/tothemoon.jpg' %}" class="card-img-top"   height="206"  alt="tothemoon">
                <div class="card-body">
                    <p class="card-text" style="color: #CDCDCD">로잘린 박사와 와츠 박사는 특이한 직업을 가지고 있습니다: 사람들에게 다시 살아갈 기회를 주는 일이죠. 맨 처음부터... 하지만 그 모든 과정은 오직 환자의 뇌 속에서만 벌어집니다. 수술의 위험성 ...</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="http://127.0.0.1:8000/game/5/detail/" class="btn btn-warning" style="font-weight: bold">자세히 보기</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<br>
<br>
<br>
{% endblock content %}

mysite/templates/introduce.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="card-group">
  <div class="card">
    <img src="{% static 'images/p의거짓.png' %}" height="400" class="card-img-top" alt="P의거짓">
    <div class="card-body">
      <h5 class="card-title">P의 거짓</h5>
      <p class="card-text">Lies Of P는 벨에포크 시대를 배경으로 펼쳐지는 잔혹동화 액션 게임입니다. 아름다웠던 도시는 흉물로 변했고 절규가 멈추지 않는 인간성 상실의 시대가 되었습니다. 고전 피노키오를 성인 잔혹극으로 각색한 Lies Of P는 매력적인 시나리오와 긴장감 넘치는 소울라이크 액션을 선사합니다. 인간이 되기 위한 여정을 떠나는 피노키오의 잔혹한 내일을 경험하세요.</p>
      <p class="card-text"><small class="text-muted">출시일 : 2023. 9. 19</small></p>
    </div>
  </div>
  <div class="card">
    <img src="{% static 'images/suicidesquad.png' %}"  height="400" class="card-img-top" alt="suicidesquad">
    <div class="card-body">
      <h5 class="card-title">수어사이드 스쿼드: 킬 더 저스티스 리그</h5>
      <p class="card-text">아캄버스의 개발사 락스테디 스튜디오의 수어사이드 스쿼드 기반 게임.</p>
      <p class="card-text"><small class="text-muted">출시일 : 2024년 2월 2일</small></p>
    </div>
  </div>
  <div class="card">
    <img src="{% static 'images/starfield.png' %}"  height="400" class="card-img-top" alt="starfield">
    <div class="card-body">
      <h5 class="card-title">스타필드</h5>
      <p class="card-text">Starfield는 The Elder Scrolls V: Skyrim과 Fallout 4로 수상 경력에 빛나는 Bethesda Game Studios가 25년만에 선보이는 새로운 세계입니다. 별들 사이에서 진행되는 이 차세대 롤플레잉 게임에서 플레이어들은 인류의 가장 큰 의문을 풀기 위한 장대한 여정을 떠나게 됩니다.</p>
      <p class="card-text"><small class="text-muted">출시일 : 2023. 9. 6.</small></p>
    </div>
  </div>
</div>
<div class="card-group">
  <div class="card">
    <img src="{% static 'images/reddessert.png' %}" height="400" class="card-img-top" alt="reddessert">
    <div class="card-body">
      <h5 class="card-title">붉은 사막</h5>
      <p class="card-text">광대하지만 분열된 대륙. 차가운 사막. 화려하지만 거친 도시. 붉은사막은 광활한 파이웰 대륙에서 펼쳐지는 개인과 세계에 대한 이야기입니다. 당신은 때로 다른 플레이어들과 경쟁하고, 때로는 협력하면서 오픈월드를 모험하고, 고대의 미스터리를 파헤칠 수 있습니다. 의도하든, 의도하지 않았든 당신은 이 세계의 역사와 운명에 깊숙이 관여하게 됩니다. 세계의 역사를 만드십시오.

이곳이 당신의 역사가 쓰일 붉은사막입니다.</p>
      <p class="card-text"><small class="text-muted">출시일 : 2023년 4분기</small></p>
    </div>
  </div>
  <div class="card">
    <img src="{% static 'images/atlas.png' %}"  height="400" class="card-img-top" alt="atlas">
    <div class="card-body">
      <h5 class="card-title">아틀라스 폴른</h5>
      <p class="card-text">유해 속에서 일어나 고대의 위험과 신비, 과거의 단편이 가득한 영원한 땅의 모래를 타고 미끄러지세요. 초능력이 사용되는 장대한 전투에서 모래의 힘이 담긴 강력한 변형 무기와 능력을 써서 전설의 괴수를 사냥하세요.</p>
      <p class="card-text"><small class="text-muted">출시일 : 2023. 8. 10</small></p>
    </div>
  </div>
  <div class="card">
    <img src="{% static 'images/stalker2.png' %}"  height="400"  class="card-img-top" alt="stalker2">
    <div class="card-body">
      <h5 class="card-title">스토커2: 초르노빌의 심장부</h5>
      <p class="card-text">우크라이나 게임 개발사 GSC Game World가 개발한 스토커 시리즈의 네번째 작품이자 3편 후로 죽은 줄 알았던 시리즈의 11년만에 귀환한 최신작.</p>
      <p class="card-text"><small class="text-muted">출시일 : 2023. 12. ??</small></p>
    </div>
  </div>
</div>
{% endblock content %}

mysite/templates/navbar.html
{% load static %}
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:startpage' %}"><img src="{% static 'images/logo.jpg' %}" class="d-block w-100" alt="..."></a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'game:list' %}">게임 목록</a>
                </li>&nbsp;&nbsp;
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pybo:index' %}">커뮤니티</a>
                </li>&nbsp;&nbsp;
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pybo:introduce' %}">출시예정작</a>
                </li>&nbsp;&nbsp;
                <li class="nav-item">
                    {% if user.is_superuser %}
                    <a class="nav-link" href="{% url 'game:game_create' %}">게임 등록</a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>